# Generated by Django 4.2.7 on 2026-07-24 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0029_application_student_application'),
        ('academics', '0012_alter_courseunit_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('required_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='academics.student')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.studyyear')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('YEARLY', 'Per Year'), ('SEMESTERLY', 'Per Semester')], default='SEMESTERLY', help_text='How often this fee is charged: once, every academic year, or every semester.', max_length=15)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0.0, help_text="Standard fee amount charged for this payment type. Used to auto-generate ledgers on enrollment. Ignored if 'Is tuition' is checked (tuition uses CourseFee instead).", max_digits=10)),
                ('is_tuition', models.BooleanField(default=False, help_text="Mark this payment type as the one representing course tuition fees. Its amount will be pulled from CourseFee (matched by student's course, academic year and semester) instead of default_amount.")),
                ('courses', models.ManyToManyField(blank=True, help_text='Courses this payment type applies to. Leave empty to apply to all courses.', related_name='payment_types', to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTypeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_type_breakdowns', to='finance.ledger')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.enrollment')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.ledger')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='academics.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.studyyear')),
            ],
            options={
                'unique_together': {('course', 'study_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Optional override for the student's fee amount. Leave blank to use the payment type's default or course fee.", max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to skip this fee during enrollment.')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_fees', to='admissions.student')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.paymenttype')),
            ],
            options={
                'unique_together': {('admission', 'payment_type')},
            },
        ),
    ]
