# Generated by Django 4.2.7 on 2026-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttypebreakdown',
            name='note',
            field=models.CharField(blank=True, help_text="Reason for adjusting this amount, e.g. 'Bursary award' or 'Staff child discount'.", max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttypebreakdown',
            name='standard_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='The amount originally generated on enrollment, kept so discounts can be reported.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttypebreakdown',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount charged to this student for this fee. Edit to grant a discount or waiver.', max_digits=10),
        ),
    ]
