# Generated by Django 4.2.7 on 2026-07-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('TEACHING', 'Teaching Staff'), ('NON_TEACHING', 'Non-Teaching Staff'), ('ADMINISTRATIVE', 'Administrative Staff'), ('SUPPORT', 'Support Staff')], default='TEACHING', max_length=20)),
                ('role', models.CharField(help_text='Job title or position', max_length=100)),
                ('start_date', models.DateField(help_text='Employment start date')),
                ('end_date', models.DateField(blank=True, help_text='Employment end/exit date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name/description', max_length=100)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='department',
        ),
    ]
