# Generated by Django 4.2.7 on 2026-07-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_courseunit_tutor'),
        ('staff', '0002_employee_employeedocument_remove_tutor_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department'),
        ),
    ]
