# Generated by Django 5.1.5 on 2025-01-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_course_remove_student_course_applied_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_documents',
            field=models.FileField(blank=True, null=True, upload_to='academic_documents/'),
        ),
        migrations.AddField(
            model_name='student',
            name='former_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='former_school_district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
