# Generated by Django 5.1.5 on 2025-01-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_remove_student_academic_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
    ]
