# Generated by Django 5.1.5 on 2025-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='NSIN',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
