# Generated by Django 5.1.5 on 2025-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_student_nsin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_admission',
            field=models.CharField(max_length=15),
        ),
    ]
