# Generated by Django 5.1.5 on 2025-01-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_alter_student_year_of_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Reporting_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
