# Generated by Django 5.1.5 on 2025-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_student_reporting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Reporting_date',
        ),
        migrations.AddField(
            model_name='student',
            name='reporting_date',
            field=models.DateField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
