# Generated by Django 5.1.5 on 2025-01-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_remove_student_reporting_date_student_reporting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='reporting_date',
            new_name='reporting',
        ),
    ]
