# Generated by Django 5.1.5 on 2025-01-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_alter_student_nsin_alter_student_admission_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reporting',
        ),
        migrations.AlterField(
            model_name='student',
            name='NSIN',
            field=models.CharField(blank=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
