# Generated by Django 5.1.5 on 2025-01-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_remove_student_reporting_alter_student_nsin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reporting',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
