# Generated by Django 5.1.5 on 2025-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_student_reporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reporting',
            field=models.DateField(blank=True, null=True),
        ),
    ]
