# Generated by Django 4.2.7 on 2026-07-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_alter_student_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PENDING', 'Pending'), ('DEFERRED', 'Deferred'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='ENROLLED', help_text='Current enrollment status of the student', max_length=15),
        ),
    ]
