# Generated by Django 4.2.7 on 2026-07-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_student_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PENDING', 'Pending'), ('DEFERRED', 'Deferred'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', help_text='Current enrollment status of the student', max_length=15),
        ),
    ]
