# Generated by Django 4.2.7 on 2026-07-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_alter_student_enrollment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Admission', 'verbose_name_plural': 'Admissions'},
        ),
    ]
