# Generated by Django 4.2.7 on 2026-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='NSIN',
            field=models.CharField(blank=True, default='0000', max_length=20, unique=True),
        ),
    ]
