# Generated by Django 4.2.7 on 2026-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0024_alter_student_nsin'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's"), ('MASTERS', "Master's")], default='CERTIFICATE', help_text='Academic level of the course', max_length=20),
        ),
    ]
