# Generated by Django 4.2.7 on 2026-07-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('admissions', '0025_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this course belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='staff.department'),
        ),
    ]
