# Generated by Django 4.2.7 on 2026-07-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0027_remove_course_department_alter_student_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
