# Generated by Django 4.2.7 on 2026-07-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_intake_student_intake'),
        ('admissions', '0028_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Select gender', max_length=1)),
                ('religion', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='application_photos/')),
                ('birth_district', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(max_length=15)),
                ('sponsor_name', models.CharField(max_length=100)),
                ('former_school', models.CharField(blank=True, max_length=200)),
                ('former_school_district', models.CharField(blank=True, max_length=100)),
                ('year_of_admission', models.CharField(max_length=15)),
                ('NSIN', models.CharField(blank=True, default='0000', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ADMITTED', 'Admitted')], default='PENDING', help_text='Application status', max_length=15)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the review process')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='academics.intake')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='application',
            field=models.OneToOneField(blank=True, help_text='The application this student was admitted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_student', to='admissions.application'),
        ),
    ]
