# Generated by Django 4.2.7 on 2026-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0030_add_application_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='NSIN',
            field=models.CharField(blank=True, default='', help_text='National Student Identification Number. Leave blank if not yet assigned.', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='NSIN',
            field=models.CharField(blank=True, default='', help_text='National Student Identification Number. Leave blank if not yet assigned.', max_length=20),
        ),
    ]
