# Generated by Django 5.1.5 on 2025-01-19 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_semester_remove_enrollment_course_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseunit')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.enrollment')),
            ],
        ),
    ]
