# Generated by Django 4.2.7 on 2026-07-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_student_enrollment_status'),
        ('staff', '0001_initial'),
        ('academics', '0003_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_units', to='admissions.course'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='course_units', to='staff.department'),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.tutor'),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear'),
        ),
    ]
