# Generated by Django 4.2.7 on 2026-07-15 10:14

from django.db import migrations, models
import django.db.models.deletion


def create_academic_students(apps, schema_editor):
    """Create an academic Student for every admission Student so foreign keys can be remapped."""
    Admission = apps.get_model('admissions', 'Student')
    AcademicStudent = apps.get_model('academics', 'Student')
    for admission in Admission.objects.all():
        AcademicStudent.objects.get_or_create(admission=admission)


def update_enrollment_student_ids(apps, schema_editor):
    """Remap Enrollment.student_id from admissions.Student to academics.Student."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE academics_enrollment
            SET student_id = (
                SELECT id FROM academics_student WHERE admission_id = academics_enrollment.student_id
            )
            WHERE student_id IS NOT NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_alter_student_options'),
        ('academics', '0004_courseunit_courses_courseunit_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.OneToOneField(help_text='The admission record this enrolled student was created from', on_delete=django.db.models.deletion.CASCADE, related_name='academic_student', to='admissions.student')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.RunPython(create_academic_students),
        migrations.RunPython(update_enrollment_student_ids),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student'),
        ),
    ]
