# Generated by Django 4.2.7 on 2026-07-15 10:34

from django.db import migrations, models


def populate_reg_numbers(apps, schema_editor):
    """Generate registration numbers for existing academic students."""
    Student = apps.get_model('academics', 'Student')
    for student in Student.objects.filter(models.Q(reg_number='') | models.Q(reg_number__isnull=True)):
        student.reg_number = f"REG-{student.id:04d}"
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_student_alter_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_number',
            field=models.CharField(blank=True, help_text='Auto-generated registration number shown when NSIN is not available', max_length=20, null=True),
        ),
        migrations.RunPython(populate_reg_numbers),
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(blank=True, help_text='Auto-generated registration number shown when NSIN is not available', max_length=20, unique=True),
        ),
    ]
