# Generated by Django 4.2.7 on 2026-07-21 05:22

from django.db import migrations, models
import django.db.models.deletion


def copy_courses_from_admissions(apps, schema_editor):
    """Copy Course data from admissions to academics"""
    AdmissionCourse = apps.get_model('admissions', 'Course')
    AcademicCourse = apps.get_model('academics', 'Course')

    for admission_course in AdmissionCourse.objects.all():
        AcademicCourse.objects.create(
            name=admission_course.name,
            short_name=admission_course.short_name,
            duration=admission_course.duration,
            level=admission_course.level,
            department=admission_course.department,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('academics', '0007_enrollment_created_at'),
        ('admissions', '0026_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('duration', models.IntegerField(help_text='Duration in months')),
                ('level', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's"), ('MASTERS', "Master's")], default='CERTIFICATE', help_text='Academic level of the course', max_length=20)),
                ('department', models.ForeignKey(blank=True, help_text='Department this course belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='staff.department')),
            ],
        ),
        migrations.RunPython(copy_courses_from_admissions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='courseunit',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_units', to='academics.course'),
        ),
    ]
