# Generated by Django 4.2.7 on 2026-07-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_course_alter_courseunit_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Intake name, e.g., January 2026 Intake', max_length=100)),
                ('start_date', models.DateField(help_text='Start date for this intake')),
                ('end_date', models.DateField(help_text='Application deadline for this intake')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('UPCOMING', 'Upcoming')], default='UPCOMING', max_length=15)),
                ('description', models.TextField(blank=True, help_text='Description of the intake')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Intake',
                'verbose_name_plural': 'Intakes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='intake',
            field=models.ForeignKey(blank=True, help_text='The intake this student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.intake'),
        ),
    ]
