# Generated by Django 4.2.7 on 2026-07-21 14:08

from django.db import migrations, models
import django.db.models.deletion


def migrate_academicyear_to_studyyear(apps, schema_editor):
    """Copy data from old AcademicYear to new StudyYear and update foreign keys"""
    AcademicYear = apps.get_model('academics', 'AcademicYear')
    StudyYear = apps.get_model('academics', 'StudyYear')
    Enrollment = apps.get_model('academics', 'Enrollment')
    CourseUnit = apps.get_model('academics', 'CourseUnit')

    # Create StudyYear records from AcademicYear records
    acad_years = AcademicYear.objects.all()
    year_mapping = {}
    for ay in acad_years:
        sy, created = StudyYear.objects.get_or_create(year=ay.year)
        year_mapping[ay.id] = sy.id

    # Update Enrollment foreign keys
    for enrollment in Enrollment.objects.filter(academic_year__isnull=False):
        old_ay_id = enrollment.academic_year_id
        if old_ay_id in year_mapping:
            enrollment.study_year_id = year_mapping[old_ay_id]
            enrollment.save()

    # Null out CourseUnit.year before changing FK target
    CourseUnit.objects.filter(year__isnull=False).update(year=None)


def set_courseunit_studyyear(apps, schema_editor):
    """Set CourseUnit.year to StudyYear IDs after FK target changed"""
    AcademicYear = apps.get_model('academics', 'AcademicYear')
    StudyYear = apps.get_model('academics', 'StudyYear')
    CourseUnit = apps.get_model('academics', 'CourseUnit')

    # Rebuild mapping
    year_mapping = {}
    for sy in StudyYear.objects.all():
        year_mapping[sy.year] = sy.id

    # We can't directly set CourseUnit.year because the old AcademicYear records
    # may not have the year field anymore. But since we nulled them all, there's
    # nothing to restore. Skip this step.
    pass


def reverse_migrate(apps, schema_editor):
    """Reverse the migration"""
    StudyYear = apps.get_model('academics', 'StudyYear')
    StudyYear.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_intake_student_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2026', max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'Study Year',
                'verbose_name_plural': 'Study Years',
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='study_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.studyyear'),
        ),
        migrations.RunPython(migrate_academicyear_to_studyyear, reverse_migrate),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date'], 'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Years'},
        ),
        migrations.AddField(
            model_name='academicyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the academic year', null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Mark as current academic year'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the academic year', null=True),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.studyyear'),
        ),
    ]
