# Generated by Django 4.2.7 on 2026-07-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_employee_employeedocument_remove_tutor_department'),
        ('academics', '0011_remove_old_academicyear_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseunit',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee'),
        ),
    ]
